### ISSUE TITLE
How to read the status of an output pin

### ISSUE THREAD

**Issue by shaliko** [ClockVapor/rpi_gpio#14]
Will be useful to be able to “read” status of output pin (High/Low).

In Python version you can do [that by this syntax](https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/):

```
GPIO.input(PIN_NUM)
```

I checked specs and not found an option for reading status of an output pin. 

based on source code of high?/low? methods  working only with "Input".

**Comment by sintro** [comment]
Same question.

**Comment by ClockVapor** [comment]
I updated the latest version to support this. Take a look and let me know if all is good!
