### ISSUE TITLE
is this only for raspberry pi?

### ISSUE THREAD

**Issue by polarspetroll** [ClockVapor/rpi_gpio#21]
Hi, i was wondering to use this library for raspberrypi , but i needed to contribute between raspi gpio pins and other micro controller such as ESP8266 , is controlling pins on other modules possible with this library? and is it same usage as raspberrypi?

**Comment by egor-khanko** [comment]
This library is ruby gem, so you **can't** use it with ESP8266 :)
Because you can't run ruby on ESP.
