### ISSUE TITLE
wrong commit author

### ISSUE THREAD

**Issue by iohzrd** [ClockVapor/rpi_gpio#7]
Hey man, I hate to bug you with this but my commit/pull request was submitted with the wrong git author/email. I know it's inconvenient but I would greatly appreciate if you would roll back to before my pull request so I can create a new one with my updated settings. I have already fixed it on my end.

**Comment by ClockVapor** [comment]
Sorry for the delay. And no worries, I'll roll it back sometime tomorrow.

**Comment by iohzrd** [comment]
Thanks bro, no rush, I appreciate it.

**Comment by ClockVapor** [comment]
And by "tomorrow," I meant "in 11 days." :stuck_out_tongue:

It's rolled back now.

**Comment by ClockVapor** [comment]
Just noticed that your PR didn't have you as an author again for some reason. Let me know if you want to try again so I can roll back before you make your changes on your fork,
